version: '3'
services:
  client:
    container_name: client
    build:
      context: ./sport-results-client
      dockerfile: ./Dockerfile
    volumes:
      - ./sport-results-client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - net
    depends_on:
      - server
  server:
    build:
      context: ./sport-results-server
      dockerfile: ./Dockerfile
    container_name: server
    volumes:
      - ./sport-results-server:/app
      - /app/node_modules
    networks:
      - net
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_DB: sport-server
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - net
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - client
      - server
      - adminer
    networks:
      - net
  adminer:
    image: adminer
    networks:
      - net
    depends_on:
      - db
volumes:
  postgres_data:
networks:
  net:
    driver: bridge
